server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}

#helloservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #自定义ribbon的规则，默认轮询,helloservice是应用名，区分大小写

feign:
  hystrix:
    enabled: true #开启服务熔断器


#引入spring-boot-starter-actuator后，注册到eureka的服务可以在euraka页面跳转到info页面
info:
  app: costomer
  log: info信息
  application-name: ${spring.application.name}
  server.port: ${server.port}

spring:
  application:
    name: hellocustomer
  zipkin:     #链路追踪支持
    base-url: http://localhost:9411
  boot:
      admin:
        client:
          url: http://localhost:7005