server:
  port: 7004

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:allenpwd/springCloudConfig.git #ssh方式制定git地址，gitee报错：com.jcraft.jsch.JSchException: reject HostKey: gitee.com原因不明
