server:
  port: 7004

spring:
  application:
    name: config
  profiles:
#    active: native  #让config使用本地文件系统的存储方式来保存配置信息
  cloud:
    config:
      server:
        git:
          #ssh方式指定git地址，支持通配符，可以使用{application}（客户端的应用名）、{profile}、{label}占位符
#          uri: git@gitee.com:allenpwd/springcloud-190926.git
          #指定本地的git仓库，指定有.git的目录，本地调试常用
          uri: file://${user.dir}
          #将配置定位到仓库的子目录，支持占位符
          search-paths:
            - config
          #存储仓库的本地路径
#          basedir: C:\Users\Administrator\Desktop\temp
          #之前gitee报错：com.jcraft.jsch.JSchException: reject HostKey: gitee.com原因不明，后面突然不会了
          strict-host-key-checking: true
        native:
          #指定本地文件系统的搜索配置文件的路径，默认[classpath:/,classpath:/config/,file:./,file:./config/]
          search-locations:
#            - file:${user.dir}/config
        #配置共同属性，即会发给所有客户端的属性
        overrides:
          or_name: ouLiGei
          or_title: 属性覆盖


  http:
    encoding:
      force: true   #加上后直接在页面访问配置中文不会乱码
#      charset: UTF-8
#      enabled: true
  zipkin:     #链路追踪支持
      base-url: http://localhost:9411
  boot:
      admin:
        client:
          url: http://localhost:7005
  #设置security安全保护
  security:
    user:
      name: user
      password: 123456

