spring:
  application:
    name: springcloud-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#新版本要加上下面的配置
management:
  metrics:
    web:
      server:
        auto-time-requests: false