spring:
  profiles:
    active:
      - dev
  zipkin:
    base-url: http://localhost:9411 #链路追踪支持

---
info:
  pwd:
    test: this is dev
spring:
  profiles: dev
server:
  port: 3355
---
spring:
  profiles: test
info:
  pwd:
    test: this is test