spring:
  profiles:
    active: dev

  #链路追踪支持
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #配置接口全部采样，默认0.1
      probability: 1.0

  #配置Spring Boot Admin服务监控
  boot:
    admin:
      client:
        url: http://localhost:7005

  rabbitmq:
#    host: 192.168.118.102
    host: 172.18.8.58

#引入spring-boot-starter-actuator后，注册到eureka的服务可以在euraka页面跳转到info页面
info:
  application-name: ${spring.application.name}
  server.port: ${server.port}
  spring-cloud-client-hostname: ${spring.cloud.client.hostname}

---
info:
  pwd:
    test: this is dev
spring:
  profiles: dev
server:
  port: 3355
  #使用{cipher}前缀来标注该内容是个加密值，会被解密
  encrypt: '{cipher}AQACpNmQ4KQxq2zu2a3I5KpvbPY9mqVkGH2scaEX+/Y2hhE3bR6+rzb/CD62+xljzFjvwJv97fjl2Nvo8ToQY0pcRnxXwd7X6yhvjRh/UOWCKlUG35Zw/gFmaDq70XZTiwxco2z8IkcN8Y6W+L4WaA40teJpKtV2DqAgsvX522lHTpDFl/8V6f4ASKoBw2uQQcmebhYIUYEYGMpoj5m92tPgBTGtyZ3RbGsAkTjw1SrIgDE6xQXJSCsL+BLubRRXIlFmyzB3DjgTmL+BBFCwkCp+oBIx0Dg2a8RE1v2pAWpBAX6BWHLLmkbEhH1tHv1EcP7ZEZ7PZodnuoEFiMRTmp6BDM7CilF8s5xDoVoVx6smc/DZneidQqBed8cgljonlQ0='
#  encrypt: '{cipher}840f8df59c63ba5e7ec32435a5df03e50049f3dbdd47912ab884a6ec98e844aa' #对称加密形式
---
spring:
  profiles: test
info:
  pwd:
    test: this is test