#处理zuul转发超时情况
hystrix:
  command:
    #配置默认的命令属性，可参考配置类HystrixCommandProperties
    default:
      execution:
        isolation:
          thread:
            #设置HystrixCommand执行的超时时间，超过该值Hystrix会将该执行命令标记为Timeout并进入服务降级处理逻辑，默认1000
            timeoutInMilliseconds: 5000
ribbon:
#  ConnectTimeout: 1000
  ReadTimeout: 2000

zuul:
  routes:
    myConfig:
      path: /myConfig/**
      url: forward:/localForward


spring:
  profiles:
    active: dev

  #链路追踪支持
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #配置接口全部采样，默认0.1
      probability: 1.0

  #配置Spring Boot Admin服务监控
  boot:
    admin:
      client:
        url: http://localhost:7005

  rabbitmq:
    host: 192.168.118.102
#    host: 172.18.8.58

#引入spring-boot-starter-actuator后，注册到eureka的服务可以在euraka页面跳转到info页面
info:
  application-name: ${spring.application.name}
  server.port: ${server.port}
  spring-cloud-client-hostname: ${spring.cloud.client.hostname}