spring:
  application:
    name: helloservice
  zipkin:     #链路追踪支持
    base-url: http://localhost:9411
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

info:
  app: provider
  log: info信息
  application-name: ${spring.application.name}
  server.port: ${server.port}