spring:
  application:
    name: helloservice
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

