server:
  port: 3356 #config server上配置的是3355，所以最终端口是3355

#配置actuator
management:
  endpoint:
    health:
      ##是config的ConfigServer端点能在health端点里看到
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - refresh #该端点用于实现客户端应用配置信息的重新获取和刷新
          - health
          - info
          - bus-refresh

#是否开启config的健康监测，默认开启，位于health端点的configServer
health:
  config:
    enabled: true

#springcloud bus结合config，以rabbitmq作为消息代理，实现应用配置的更新
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    bus:
      trace:
        enabled: false