server:
  port: 7007

spring:
  application:
    name: bus
  #配置rabbitmq
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#    register-with-eureka: false

#配置actuator
management:
  endpoint:
    health:
      ##是config的ConfigServer端点能在health端点里看到
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - bus-refresh #该端点用于向bus消息总线发布更新信息，比如发到rabbitmq，所有监听该rabbitmq的client都会收到消息从而可以更新配置
