server:
  port: 7007

spring:
  application:
    name: bus
  #配置rabbitmq
  rabbitmq:
    addresses: 172.18.8.58
    username: guest
    password: guest
    port: 5672


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#    register-with-eureka: false

#配置actuator
management:
  endpoint:
    health:
      ##是config的ConfigServer端点能在health端点里看到
      show-details: always
